# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "qrcodescanner-app"
client_id = "05ba8b5d3c8a3ccfbbeb1434947ebf20"
application_url = "https://mixture-stock-memories-fall.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mixture-stock-memories-fall.trycloudflare.com/auth/callback",
  "https://mixture-stock-memories-fall.trycloudflare.com/auth/shopify/callback",
  "https://mixture-stock-memories-fall.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-6e6b55c3.myshopify.com"
